# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Up Next
email: hello@burnish.cc
description: > # this means to ignore newlines until "baseurl:"
  Up Next is a simple app for listening to podcasts episode by episode.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://burnish.cc" # the base hostname & protocol for your site
twitter_username: blackp
github_username:  burnish

# Build settings
markdown: kramdown
